# Dependencies
gems:
  - jekyll-sitemap
  - jekyll-paginate

# Permalinks
permalink:           pretty

# Setup
url:                 http://wythoff.net

# Set to '' in case of hosting on GitHub pages,
# i.e. `http://<username>.github.io`
baseurl:

title:               Grant Wythoff

# Pagination
paginate:            5
paginate_path:       '/page-:num/'

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:         >
  Postdoctoral fellow at Columbia University studying media, technology, and culture through the lens of science fiction.

# The tags listed as entries in the sidebar
sidebar_tags:        []

# Fallback image and color if not overwritten for tag or post
image:               /public/img/spaceman.jpg
color:               '#A85641'

# Fonts
font:                '"PT Serif", Georgia, serif'
font_accent:         '"Roboto Slab", "PT Serif", Georgia, serif'
load_google_fonts:   'Roboto+Slab:700|PT+Serif:400,400italic,700,700italic'

# About yourself
author:
  name:              'Grant Wythoff'

  # This photo will be used in the about section
  photo:             /public/img/grant.jpg
  photo2x:           /public/img/grant.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:             |
    I am a Visiting Fellow with the [Center for Humanities and Information](chi.la.psu.edu) at Pennsylvania State University.

    I study the history and philosophy of media technologies, twentieth century American literature, and digital approaches to humanities research. My work is fundamentally about the relationship between our tools, their intellectual histories, and what we imagine those tools to be capable of in daily practice.

    My recent book, [*The Perversity of Things: Hugo Gernsback on Media, Tinkering, and Scientifiction*](https://www.upress.umn.edu/book-division/books/the-perversity-of-things) (University of Minnesota Press, 2016), explores how science fiction began in the 1910s among a community of tinkerers trying to imagine the future of media technologies through making. It has been reviewed in the [*New York Review of Books*](http://www.nybooks.com/daily/2017/01/31/hugo-gernsback-making-of-future-man/) (James Gleick), [*Leonardo*](http://leonardo.info/reviews/feb2017/gernsback-wythoff.php), and [*Kirkus Reviews*](https://www.kirkusreviews.com/features/learn-more-about-creators-science-fiction/), among other places. I have been interviewed about this project for documentary films by Minna Långström, Eric Schockmel, and a television miniseries that will air on AMC titled *James Cameron's Story of Science Fiction.*

    At Columbia, I was a co-founder of the [Group for Experimental Methods in the Humanities](http://xpmethod.plaintext.in/), and organized a lecture series on the [History of Method in the Humanities](http://societyoffellows.columbia.edu/events/semester/spring-2015/on-method-workshops/) as well as a conference that put media archaeologists into conversation with "stones and bones" archaeologists, titled [Insuetude: Conversations in Technological Discard and Archaeological Recuperation.](http://societyoffellows.columbia.edu/events/insuetude/)

    Previously, I served on the steering committee of the Princeton [Digital Humanities Initiative](http://digitalhumanities.princeton.edu/), and was project manager on [Princeton Prosody Archive](http://prosody.princeton.edu/), a full-text searchable database of writing on the rhythm, intonation, and utterance of language from 1750-1950, under the direction of [Meredith Martin](http://english.princeton.edu/people/meredith-martin).

    View my full [CV here.](http://wythoff.net/cv)

  # Social media icons in sidebar
  # Comment/uncommet to show/hide
  # Icons appear in order, can be rearranged:
  social:
    facebook:        gwijthoff
    twitter:         gwijthoff
    #academia:        GrantWythoff
    #google:          _number_
    #vk:              _username_
    #youtube:         _string___string___string_
    # vimeo:           _username_
    # vine:            _username_
    # spotify:         user/_number_
    # soundcloud:      _username_
    # lastfm:          _username_
    # instagram:       _username_
    # flickr:          _string_@_string_
    # 500px:           _username_
    # dribbble:        _username_
    # behance:         _username_
    # deviantart:      _username_
    # ello:            _username_
    # twitch:          _username_
    # steam:           _number_
    # reddit:          _username_
    # tumblr:          _username_
    # pinterest:       _username_
    # foursquare:      _number_
    # yelp:            _string_
    github:          gwijthoff
    # stackoverflow:   _number_/_username_
    # npm:             _username_
    # hackernews:      _username_
    # trello:          _firstname__lastname_
    # linkedin:        _firstname_-_lastname_-_string_
    # xing:            _firstname___lastname__counter_
    # blogger:         _number_
    # delicious:       _username_
    # stumbleupon:     _username_
    # paypal:          _username_

# Remove to disable Google Anaylics
# now using my old one from wythoff.net
google_analytics_id: 'UA-11942763-2'

# Setting a disqus subdomain will enable the comment section
# disqus:            <username>

kramdown:
  math_engine:       mathjax
  math_engine_opts:
    preview:         true
    preview_as_code: true

compress_html:
  comments:          ["<!-- ", " -->"]
  clippings:         all
  endings:           all
  ignore:
    envs:            [local]

sass:
  style:             compressed
